name: HelloWOrld                                  # workflow name
 
on:
  push:                                       
    branches:                                 
      - main
 
jobs:
  build:
    runs-on: ubuntu-20.04                 
    steps:
      - run: echo "This is a build step"     
 
  test:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - run: echo "This is a test step"
 
  integration:
    runs-on: ubuntu-20.04
    needs: container_scanning
    steps:
      - run: echo "This is an integration step"
      - run: exit 1
        continue-on-error: true
 
  prod:
    runs-on: ubuntu-20.04
    needs: integration
    steps:
      - run: echo "This is a deploy step"
